name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: adopt

      - name: Build PlaceholderAPI
        run: ./gradlew build

      - name: Upload PlaceholderAPI
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "LimboAuth"
          automatic_release_tag: "la"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: false
